### PR TITLE
replaceAll is now available on SetColl

### PR DESCRIPTION
**Pull request by NeilRashbrook**
So my previous workarounds are no longer necessary.

### CODE REVIEW

**Comment by NeilRashbrook** [comment]
(As of commit 2b1765b.)

**Comment by benbucksch** [comment]
I assume you tested this.
review+

**Comment by benbucksch** [comment]
@NeilRashbrook Did you test this?

image

**Comment by benbucksch** [comment]
Set.replaceAll() was not actually working. I added it now to the library.

@NeilRashbrook Next time, please test your changes before you submit them.

**Comment by benbucksch** [comment]
Fixed in git commit 9a979ef6 and [in the library](https://github.com/benbucksch/jscollection/commit/9886da00af8c64fec7654219c9d74b1983c6b7e3)

**Pull request merged**
