### PR TITLE
OAuth2Window: Close window from main process #210

### PR DESCRIPTION
**Pull request by jermy-c**
- Sends IPC message to the main process to close the window from there

### CODE REVIEW

**Comment by benbucksch** [comment]
Why?

**Comment by jermy-c** [comment]
> Why? Can you please describe the specific bug that you are trying to fix here? In which situations does it appear?

This is just a temporary workaround for a window that doesn't close with the `window.close()`. Remember the bug where the OAuth2 window doesn't close for Yahoo and AOL mail? This is a workaround for that in the meantime. It seems like when the redirect url is a different domain then window.close() doesn't work because the new domain is considered a new entry. I couldn't find a way to set the opener otherwise that would be a better solution.

> As of [Chromium 88](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/dom_window.cc;l=347;drc=e1facbdd9b6cfe6f5ec53f8b20e662c934e75045), window.close() succeeds if the new window/tab has an [opener](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) or if the back/forward stack contains fewer than two entries.

> Why do you think that this is the right fix?

I don't think this is the right fix but it is the only solution I have at the moment.

**Review by benbucksch — APPROVED** [review]
@jermy-c What happens when there are 2 windows open at the same time? Which one will it close?

This entire code should be re-written using JPC instead of Electron IPC.

**Comment by NeilRashbrook** [comment]
(The window opening side is my fault since at the time I didn't even know that JPC was running in the IPC main process.)

**Pull request merged**
