### PR TITLE
 EWS, OWA, ActiveSync: Don't compare username with emailAddress #226 

### PR DESCRIPTION
**Pull request by jermy-c**
- EWS, OWA, ActiveSync: Compare username with username

### CODE REVIEW

**Comment by benbucksch** [comment]
Looks good and correct and obvious to me. Just to double-check:

@NeilRashbrook Was there a specific reason why you compared with `this.emailAddress` instead of `this.username`? The latter seems to be obvious, so I wonder whether you had a reason to do it differently.

@jermy-c 
1. Is `this.username` correctly populated in all cases, including during startup, before this code runs? (This is a code-inspection verification.)
2. Did you test it? (This is a practical verification.)

**Comment by NeilRashbrook** [comment]
> Was there a specific reason why you compared with `this.emailAddress` instead of `this.username`? The latter seems to be obvious, so I wonder whether you had a reason to do it differently.

It's because in the dim and distant past mail account would only reliably have the email address set, as opposed to other accounts which only have a username. (In fact there is still a `this.username || this.emailAddress` in `EWSAccount.ts` which since got copied to `ActiveSyncAccount.ts`; sorry about that.) For OWA it seems that I actually ignore the username which seems to be a bug (I assume account creation will set it to be the same as the email address unless the user manually configures the account).

**Review by NeilRashbrook — APPROVED** [review]

**Comment by benbucksch** [comment]
> It's because in the dim and distant past mail account would only reliably have the email address set

@NeilRashbrook I see, thanks. Is that definitely "past" now?

**Comment by jermy-c** [comment]
> Is this.username correctly populated in all cases, including during startup, before this code runs? (This is a code-inspection verification.)
Yes.

> Did you test it? (This is a practical verification.)
EWS and OWA addressbook and calendar works for business accounts. ActiveSync is buggy because it's not showing any folders so I couldn't test the addressbook and calendar.

I didn't see any contacts or calendar events from personal accounts from any of the protocols.

**Comment by benbucksch** [comment]
@jermy-c Thanks for having checked!

**Pull request merged**
