### PR TITLE
Set channel name to mustang

### PR DESCRIPTION
**Pull request by jermy-c**
- Set channel name to `mustang`, it changes the `latest.yml` to `mustang.yml`
- The script in `app/build/parula-brand.sh` changes the channel to `parula`

### CODE REVIEW

**Comment by benbucksch** [comment]
> Let app/build/parula-brand.sh change it to parula in the Github workflow

I don't see that change in the PR. Did you mean to push that?

**Comment by jermy-c** [comment]
> > Let app/build/parula-brand.sh change it to parula in the Github workflow
> 
> I don't see that change in the PR. Did you mean to push that?

The script in `app/build/parula-brand.sh` changes the channel to `parula` already.

**Comment by benbucksch** [comment]
> I meant the script in app/build/parula-brand.sh changes the channel to parula already.

Where? I don't see it.

**Comment by jermy-c** [comment]
> Where? I don't see it.

https://github.com/mustang-im/mustang/blob/e26bbac31930e6518a0f95c093eda6a87d6dccef/app/build/parula-brand.sh#L24

**Comment by benbucksch** [comment]
Oh, I see! With the generic change of all "mustang" to "parula" in electron-builder.yml. Because the new change adds `channel: mustang`, the script would now also change this instance of "mustang". Gotcha!

**Comment by benbucksch** [comment]
Very cute. I love your minimalistic changes. This is the exactly right fix for this problem.

Very elegant! +1

**Pull request merged**
