### PR TITLE
Open links in system browser (#191)

### PR DESCRIPTION
**Pull request by jermy-c**
- Opens links in system browser
- Why did I do it this way? `did-start-navigation`,  `will-frame-navigate`, `will-navigate`, `did-frame-navigate`, `did-navigate` events don't trigger nor does `did-create-window`
- The other way might be to use `<webview>.executeJavaScript(code[, userGesture])` and have it send the URL to the main window.

### CODE REVIEW

**Comment by jermy-c** [comment]
At the moment it opens the link in the system browser without any popup or dialog asking the user whether would like to open the link externally.

**Comment by benbucksch** [comment]
How do you know that the use actually clicked on the link? And that he 
didn't move the mouse somewhere else after the first event?

**Comment by jermy-c** [comment]
Because:

- `url` would be updated to an empty string as soon as the cursor leaves the link
- if the `url` is an empty string then the click event wouldn't open the link

**Comment by jermy-c** [comment]
It opens link only on left click now but it doesn't open links when the it the link is selected/highlighted and left clicked.

**Comment by benbucksch** [comment]
You mean the text selection includes the URL? In this case, it's fine 
that the click doesn't open the URL. I'd call that a feature, because the 
user tried to select and copy the text, not open the URL.

**Comment by benbucksch** [comment]
Thank you!

**Pull request merged**
