### PR TITLE
Send all extra MIME headers

### PR DESCRIPTION
**Pull request by NeilRashbrook**
As per comments on 4477457.

(Seriously, is there no way to map over a Map?)

### CODE REVIEW

**Review by benbucksch — APPROVED** [review]

**Comment by NeilRashbrook** [comment]
(to answer my own question, with a regular `Map` I don't need `.entries`, but `MapColl` is a `Collection` so its API differs)

**Comment by benbucksch** [comment]
@NeilRashbrook Thanks.
* It now works in OWA for me.
* No observable change in EWS
* In both cases, the header name is sent in all lower case. OK for now.

**Comment by NeilRashbrook** [comment]
I doubt we can do anything about that unless you're prepared to convert the message to MIME first (which we'll need to do for ActiveSync anyway).

**Comment by benbucksch** [comment]
It's OK, it's Good Enough (TM)

**Pull request merged**
